const bcrypt = require('bcryptjs');

exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('reviews').del();
  await knex('bookings').del();
  await knex('properties').del();
  await knex('users').del();

  // Hash passwords
  const hashedPassword = await bcrypt.hash('password123', 10);
  // Insert users
  const users = await knex('users').insert([
    {
      id: 1,
      first_name: 'Admin',
      last_name: 'User',
      email: 'admin@kostra.com',
      password: hashedPassword,
      phone: '+977-9800000000',
      role: 'admin',
      is_verified: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 2,
      first_name: 'John',
      last_name: 'Host',
      email: 'john@example.com',
      password: hashedPassword,
      phone: '+977-9800000001',
      role: 'host',
      is_verified: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 3,
      first_name: 'Jane',
      last_name: 'Guest',
      email: 'jane@example.com',
      password: hashedPassword,
      phone: '+977-9800000002',
      role: 'guest',
      is_verified: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 4,
      first_name: 'Rajesh',
      last_name: 'Sharma',
      email: 'rajesh@example.com',
      password: hashedPassword,
      phone: '+977-9800000003',
      role: 'host',
      is_verified: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 5,
      first_name: 'Maya',
      last_name: 'Thapa',
      email: 'maya@example.com',
      password: hashedPassword,
      phone: '+977-9800000004',
      role: 'host',
      is_verified: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 6,
      first_name: 'David',
      last_name: 'Wilson',
      email: 'david@example.com',
      password: hashedPassword,
      phone: '+977-9800000005',
      role: 'host',
      is_verified: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 7,
      first_name: 'Sunita',
      last_name: 'Gurung',
      email: 'sunita@example.com',
      password: hashedPassword,
      phone: '+977-9800000006',
      role: 'host',
      is_verified: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 8,
      first_name: 'Michael',
      last_name: 'Brown',
      email: 'michael@example.com',
      password: hashedPassword,
      phone: '+977-9800000007',
      role: 'host',
      is_verified: true,
      created_at: new Date(),
      updated_at: new Date()
    }
  ]);
  // Insert properties
  await knex('properties').insert([
    {
      id: 1,
      host_id: 2,
      title: 'Luxury Mountain View Apartment - Kathmandu',
      description: 'Modern 3-bedroom apartment in the heart of Kathmandu with stunning mountain views. Features contemporary furnishing, high-speed internet, and proximity to major business districts. Perfect for both short stays and long-term rentals.',
      type: 'apartment',
      address: 'Durbar Marg, Kathmandu',
      city: 'Kathmandu',
      state: 'Bagmati',
      country: 'Nepal',
      zip_code: '44600',
      latitude: 27.7017,
      longitude: 85.3206,
      price: 25000.00,
      currency: 'NPR',
      bedrooms: 3,
      bathrooms: 2,
      max_guests: 6,
      amenities: JSON.stringify(['Wi-Fi', 'Mountain View', 'Air Conditioning', 'Parking', 'Kitchen', 'Balcony', 'Elevator']),
      images: JSON.stringify(['/placeholder.svg?height=200&width=300']),
      availability: true,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 2,
      host_id: 4,
      title: 'Cozy Studio in Thamel - Tourist Hub',
      description: 'Compact yet comfortable studio apartment in the vibrant Thamel district. Walking distance to restaurants, shops, and cultural sites. Ideal for solo travelers and couples.',
      type: 'apartment',
      address: 'Thamel Marg, Kathmandu',
      city: 'Kathmandu',
      state: 'Bagmati',
      country: 'Nepal',
      zip_code: '44600',
      latitude: 27.7147,
      longitude: 85.3142,
      price: 15000.00,
      currency: 'NPR',
      bedrooms: 1,
      bathrooms: 1,
      max_guests: 2,
      amenities: JSON.stringify(['Wi-Fi', 'Kitchen', 'Hot Water', 'Tourist Area', 'Restaurant Access']),
      images: JSON.stringify(['/placeholder.svg?height=200&width=300']),
      availability: true,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 3,
      host_id: 5,
      title: 'Lakeside Villa - Pokhara Premium',
      description: 'Stunning 4-bedroom villa directly on Phewa Lake with panoramic views of the Annapurna range. Private garden, boat access, and luxury amenities. Perfect for families and groups.',
      type: 'villa',
      address: 'Lakeside-6, Pokhara',
      city: 'Pokhara',
      state: 'Gandaki',
      country: 'Nepal',
      zip_code: '33700',
      latitude: 28.2096,
      longitude: 83.9856,
      price: 45000.00,
      currency: 'NPR',
      bedrooms: 4,
      bathrooms: 3,
      max_guests: 8,
      amenities: JSON.stringify(['Lake View', 'Wi-Fi', 'Private Garden', 'Boat Access', 'Kitchen', 'Fireplace', 'BBQ Area']),
      images: JSON.stringify(['/placeholder.svg?height=200&width=300']),
      availability: true,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 4,
      host_id: 6,
      title: 'Traditional Newari House - Bhaktapur',
      description: 'Experience authentic Nepali culture in this beautifully restored traditional Newari house. Located in the historic Bhaktapur Durbar Square area with traditional architecture and modern comfort.',
      type: 'house',
      address: 'Durbar Square, Bhaktapur',
      city: 'Bhaktapur',
      state: 'Bagmati',
      country: 'Nepal',
      zip_code: '44800',
      latitude: 27.6710,
      longitude: 85.4298,
      price: 18000.00,
      currency: 'NPR',
      bedrooms: 2,
      bathrooms: 2,
      max_guests: 4,
      amenities: JSON.stringify(['Cultural Experience', 'Wi-Fi', 'Traditional Architecture', 'Heritage Site', 'Courtyard']),
      images: JSON.stringify(['/placeholder.svg?height=200&width=300']),
      availability: true,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 5,
      host_id: 7,
      title: 'Mountain Lodge - Nagarkot Sunrise Point',
      description: 'Wake up to breathtaking Himalayan sunrises from this mountain lodge. Features panoramic mountain views, traditional hospitality, and access to hiking trails.',
      type: 'cabin',
      address: 'Nagarkot Hill Station',
      city: 'Nagarkot',
      state: 'Bagmati',
      country: 'Nepal',
      zip_code: '44600',
      latitude: 27.7172,
      longitude: 85.5328,
      price: 22000.00,
      currency: 'NPR',
      bedrooms: 3,
      bathrooms: 2,
      max_guests: 6,
      amenities: JSON.stringify(['Mountain View', 'Sunrise View', 'Hiking Trails', 'Wi-Fi', 'Restaurant', 'Heater']),
      images: JSON.stringify(['/placeholder.svg?height=200&width=300']),
      availability: true,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 6,
      host_id: 8,
      title: 'Jungle Safari Lodge - Chitwan National Park',
      description: 'Eco-friendly lodge in the heart of Chitwan National Park. Experience wildlife safaris, cultural programs, and nature walks. All-inclusive packages available.',
      type: 'villa',
      address: 'Sauraha, Chitwan National Park',
      city: 'Chitwan',
      state: 'Narayani',
      country: 'Nepal',
      zip_code: '44200',
      latitude: 27.5786,
      longitude: 84.4951,
      price: 35000.00,
      currency: 'NPR',
      bedrooms: 2,
      bathrooms: 2,
      max_guests: 4,
      amenities: JSON.stringify(['Wildlife Safari', 'National Park', 'Restaurant', 'Cultural Program', 'Nature Walks', 'All-Inclusive']),
      images: JSON.stringify(['/placeholder.svg?height=200&width=300']),
      availability: true,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 7,
      host_id: 2,
      title: 'Business District Apartment - New Baneshwor',
      description: 'Modern furnished apartment in the business district. Perfect for business travelers and professionals. High-speed internet, meeting spaces nearby, and excellent transport links.',
      type: 'apartment',
      address: 'New Baneshwor, Kathmandu',
      city: 'Kathmandu',
      state: 'Bagmati',
      country: 'Nepal',
      zip_code: '44600',
      latitude: 27.6928,
      longitude: 85.3435,
      price: 28000.00,
      currency: 'NPR',
      bedrooms: 2,
      bathrooms: 2,
      max_guests: 4,
      amenities: JSON.stringify(['Business District', 'High-Speed Wi-Fi', 'Meeting Rooms Nearby', 'Transport Links', 'Furnished', 'Parking']),
      images: JSON.stringify(['/placeholder.svg?height=200&width=300']),
      availability: true,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 8,
      host_id: 4,
      title: 'Riverside Cottage - Sarangkot',
      description: 'Peaceful cottage with river views and mountain backdrop. Perfect for meditation retreats, yoga sessions, and nature lovers seeking tranquility.',
      type: 'house',
      address: 'Sarangkot, Pokhara',
      city: 'Pokhara',
      state: 'Gandaki',
      country: 'Nepal',
      zip_code: '33700',
      latitude: 28.2423,
      longitude: 83.9525,
      price: 20000.00,
      currency: 'NPR',
      bedrooms: 2,
      bathrooms: 1,
      max_guests: 4,
      amenities: JSON.stringify(['River View', 'Mountain View', 'Meditation Space', 'Yoga Area', 'Garden', 'Peaceful Environment']),
      images: JSON.stringify(['/placeholder.svg?height=200&width=300']),
      availability: true,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 9,
      host_id: 5,
      title: 'Luxury Penthouse - Lazimpat',
      description: 'Exclusive penthouse with 360-degree city views. Premium amenities including private terrace, jacuzzi, and concierge services. Perfect for luxury stays.',
      type: 'apartment',
      address: 'Lazimpat, Kathmandu',
      city: 'Kathmandu',
      state: 'Bagmati',
      country: 'Nepal',
      zip_code: '44600',
      latitude: 27.7241,
      longitude: 85.3240,
      price: 55000.00,
      currency: 'NPR',
      bedrooms: 3,
      bathrooms: 3,
      max_guests: 6,
      amenities: JSON.stringify(['Penthouse', 'City View', 'Private Terrace', 'Jacuzzi', 'Concierge', 'Luxury Furnishing', 'Elevator']),
      images: JSON.stringify(['/placeholder.svg?height=200&width=300']),
      availability: true,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 10,
      host_id: 6,
      title: 'Family House - Patan Heritage Area',
      description: 'Spacious family house in the UNESCO World Heritage site of Patan. Traditional architecture with modern amenities, perfect for families and cultural enthusiasts.',
      type: 'house',
      address: 'Patan Durbar Square Area',
      city: 'Patan',
      state: 'Bagmati',
      country: 'Nepal',
      zip_code: '44700',
      latitude: 27.6744,
      longitude: 85.3244,
      price: 30000.00,
      currency: 'NPR',
      bedrooms: 4,
      bathrooms: 3,
      max_guests: 8,
      amenities: JSON.stringify(['Heritage Site', 'Family Friendly', 'Cultural Area', 'Traditional Architecture', 'Spacious', 'Wi-Fi']),
      images: JSON.stringify(['/placeholder.svg?height=200&width=300']),
      availability: true,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 11,
      host_id: 7,
      title: 'Adventure Base Camp - Bandipur',
      description: 'Perfect base for adventure activities in the historic hill town of Bandipur. Stunning mountain views, hiking trails, and cultural experiences.',
      type: 'cabin',
      address: 'Bandipur Bazaar',
      city: 'Bandipur',
      state: 'Gandaki',
      country: 'Nepal',
      zip_code: '33904',
      latitude: 27.9319,
      longitude: 84.4206,
      price: 16000.00,
      currency: 'NPR',
      bedrooms: 2,
      bathrooms: 1,
      max_guests: 4,
      amenities: JSON.stringify(['Adventure Activities', 'Mountain View', 'Hiking Trails', 'Historic Town', 'Cultural Experience']),
      images: JSON.stringify(['/placeholder.svg?height=200&width=300']),
      availability: true,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 12,
      host_id: 8,
      title: 'Modern Apartment - Boudha Stupa Area',
      description: 'Contemporary apartment near the famous Boudha Stupa. Experience Tibetan culture, meditation centers, and spiritual atmosphere while enjoying modern comfort.',
      type: 'apartment',
      address: 'Boudha, Kathmandu',
      city: 'Kathmandu',
      state: 'Bagmati',
      country: 'Nepal',
      zip_code: '44600',
      latitude: 27.7215,
      longitude: 85.3617,
      price: 23000.00,
      currency: 'NPR',
      bedrooms: 2,
      bathrooms: 2,
      max_guests: 4,
      amenities: JSON.stringify(['Spiritual Area', 'Boudha Stupa', 'Meditation Centers', 'Tibetan Culture', 'Wi-Fi', 'Modern Amenities']),
      images: JSON.stringify(['/placeholder.svg?height=200&width=300']),
      availability: true,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 13,
      host_id: 2,
      title: 'Garden Villa - Godavari',
      description: 'Peaceful villa surrounded by botanical gardens. Perfect retreat from city life with beautiful natural surroundings and fresh mountain air.',
      type: 'villa',
      address: 'Godavari, Lalitpur',
      city: 'Lalitpur',
      state: 'Bagmati',
      country: 'Nepal',
      zip_code: '44700',
      latitude: 27.5916,
      longitude: 85.3828,
      price: 32000.00,
      currency: 'NPR',
      bedrooms: 3,
      bathrooms: 2,
      max_guests: 6,
      amenities: JSON.stringify(['Botanical Garden', 'Natural Surroundings', 'Fresh Air', 'Peaceful', 'Garden View', 'Wi-Fi']),
      images: JSON.stringify(['/placeholder.svg?height=200&width=300']),
      availability: true,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 14,
      host_id: 4,
      title: 'Airport Hotel Suite - Sinamangal',
      description: 'Convenient hotel suite near Tribhuvan International Airport. Perfect for transit passengers and business travelers with airport shuttle service.',
      type: 'hotel',
      address: 'Sinamangal, Kathmandu',
      city: 'Kathmandu',
      state: 'Bagmati',
      country: 'Nepal',
      zip_code: '44600',
      latitude: 27.6966,
      longitude: 85.3591,
      price: 12000.00,
      currency: 'NPR',
      bedrooms: 1,
      bathrooms: 1,
      max_guests: 2,
      amenities: JSON.stringify(['Airport Nearby', 'Shuttle Service', 'Business Friendly', 'Transit Suitable', 'Wi-Fi', '24/7 Reception']),
      images: JSON.stringify(['/placeholder.svg?height=200&width=300']),
      availability: true,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 15,
      host_id: 5,
      title: 'Himalayan View Lodge - Dhulikhel',
      description: 'Spectacular Himalayan views from this mountain lodge. Watch sunrise over the peaks while enjoying traditional Nepali hospitality and organic local food.',
      type: 'cabin',
      address: 'Dhulikhel Municipality',
      city: 'Dhulikhel',
      state: 'Bagmati',
      country: 'Nepal',
      zip_code: '45200',
      latitude: 27.6217,
      longitude: 85.5442,
      price: 26000.00,
      currency: 'NPR',
      bedrooms: 2,
      bathrooms: 2,
      max_guests: 4,
      amenities: JSON.stringify(['Himalayan View', 'Sunrise View', 'Organic Food', 'Traditional Hospitality', 'Mountain Lodge', 'Peaceful']),
      images: JSON.stringify(['/placeholder.svg?height=200&width=300']),
      availability: true,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 16,
      host_id: 6,
      title: 'Riverside Resort - Trishuli',
      description: 'Adventure resort by the Trishuli River. Perfect for rafting enthusiasts and adventure seekers. Includes river activities and outdoor adventure packages.',
      type: 'villa',
      address: 'Trishuli Riverside',
      city: 'Nuwakot',
      state: 'Bagmati',
      country: 'Nepal',
      zip_code: '44900',
      latitude: 27.8831,
      longitude: 85.1747,
      price: 28000.00,
      currency: 'NPR',
      bedrooms: 3,
      bathrooms: 2,
      max_guests: 6,
      amenities: JSON.stringify(['River Rafting', 'Adventure Activities', 'Riverside Location', 'Outdoor Activities', 'Adventure Packages']),
      images: JSON.stringify(['/placeholder.svg?height=200&width=300']),
      availability: true,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 17,
      host_id: 7,
      title: 'City Center Apartment - Putalisadak',
      description: 'Prime location apartment in the heart of Kathmandu. Walking distance to shopping centers, restaurants, and major attractions. Perfect for urban explorers.',
      type: 'apartment',
      address: 'Putalisadak, Kathmandu',
      city: 'Kathmandu',
      state: 'Bagmati',
      country: 'Nepal',
      zip_code: '44600',
      latitude: 27.7060,
      longitude: 85.3157,
      price: 21000.00,
      currency: 'NPR',
      bedrooms: 2,
      bathrooms: 1,
      max_guests: 4,
      amenities: JSON.stringify(['City Center', 'Shopping Centers', 'Restaurants Nearby', 'Urban Location', 'Transport Links', 'Wi-Fi']),
      images: JSON.stringify(['/placeholder.svg?height=200&width=300']),
      availability: true,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 18,
      host_id: 8,
      title: 'Monastery Guesthouse - Kopan',
      description: 'Peaceful guesthouse near Kopan Monastery. Perfect for meditation retreats, spiritual journeys, and those seeking inner peace in a serene environment.',
      type: 'house',
      address: 'Kopan Monastery Area',
      city: 'Kathmandu',
      state: 'Bagmati',
      country: 'Nepal',
      zip_code: '44600',
      latitude: 27.7377,
      longitude: 85.3644,
      price: 14000.00,
      currency: 'NPR',
      bedrooms: 2,
      bathrooms: 1,
      max_guests: 4,
      amenities: JSON.stringify(['Monastery Nearby', 'Meditation', 'Spiritual Environment', 'Peaceful', 'Mountain View', 'Simple Living']),
      images: JSON.stringify(['/placeholder.svg?height=200&width=300']),
      availability: true,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 19,
      host_id: 2,
      title: 'Executive Suite - Hattisar',
      description: 'Luxurious executive suite in upscale Hattisar area. Features premium amenities, business facilities, and proximity to embassies and corporate offices.',
      type: 'apartment',
      address: 'Hattisar, Kathmandu',
      city: 'Kathmandu',
      state: 'Bagmati',
      country: 'Nepal',
      zip_code: '44600',
      latitude: 27.7158,
      longitude: 85.3326,
      price: 42000.00,
      currency: 'NPR',
      bedrooms: 2,
      bathrooms: 2,
      max_guests: 4,
      amenities: JSON.stringify(['Executive Suite', 'Business Facilities', 'Upscale Area', 'Embassy District', 'Premium Amenities', 'Concierge']),
      images: JSON.stringify(['/placeholder.svg?height=200&width=300']),
      availability: true,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 20,
      host_id: 4,
      title: 'Adventure Hostel - Gorkha',
      description: 'Budget-friendly accommodation perfect for trekkers and adventure enthusiasts. Base for Manaslu Circuit and other Himalayan adventures. Dormitory and private room options.',
      type: 'cabin',
      address: 'Gorkha Bazaar',
      city: 'Gorkha',
      state: 'Gandaki',
      country: 'Nepal',
      zip_code: '34000',
      latitude: 28.0000,
      longitude: 84.6253,
      price: 8000.00,
      currency: 'NPR',
      bedrooms: 1,
      bathrooms: 1,
      max_guests: 4,
      amenities: JSON.stringify(['Trekking Base', 'Adventure Hub', 'Budget Friendly', 'Manaslu Circuit', 'Mountain View', 'Trekking Gear Rental']),
      images: JSON.stringify(['/placeholder.svg?height=200&width=300']),
      availability: true,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date()
    }
  ]);
  // Insert sample bookings
  await knex('bookings').insert([
    {
      id: 1,
      user_id: 3,
      property_id: 1,
      check_in: '2024-07-01',
      check_out: '2024-07-03',
      guests: 2,
      total_price: 50000.00,
      status: 'confirmed',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 2,
      user_id: 3,
      property_id: 3,
      check_in: '2024-08-15',
      check_out: '2024-08-18',
      guests: 4,
      total_price: 135000.00,
      status: 'confirmed',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 3,
      user_id: 3,
      property_id: 5,
      check_in: '2024-09-10',
      check_out: '2024-09-12',
      guests: 2,
      total_price: 44000.00,
      status: 'completed',
      created_at: new Date(),
      updated_at: new Date()
    }
  ]);

  // Insert sample reviews
  await knex('reviews').insert([
    {
      id: 1,
      user_id: 3,
      property_id: 1,
      rating: 5,
      comment: 'Absolutely stunning apartment with amazing mountain views! The location is perfect and the amenities are top-notch. Perfect for both business and leisure stays.',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 2,
      user_id: 3,
      property_id: 3,
      rating: 5,
      comment: 'What an incredible lakeside experience! The villa exceeded all expectations. Perfect for families and the lake access made our stay unforgettable.',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 3,
      user_id: 3,
      property_id: 5,
      rating: 4,
      comment: 'Beautiful mountain lodge with spectacular sunrise views. The traditional hospitality was wonderful. Great for a peaceful mountain retreat.',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 4,
      user_id: 3,
      property_id: 6,
      rating: 5,
      comment: 'Amazing wildlife experience! The safari was incredible and the lodge provided excellent service. Perfect for nature lovers and adventure seekers.',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 5,
      user_id: 3,
      property_id: 9,
      rating: 5,
      comment: 'Luxury at its finest! The penthouse views are breathtaking and the amenities are world-class. Perfect for special occasions.',
      created_at: new Date(),
      updated_at: new Date()
    }
  ]);
};
